/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "src_verilog/mor1k_16Soc_top.v:30" *)
module mor1k_16Soc_top(clk, reset, processors_en);
  (* src = "src_verilog/mor1k_16Soc_top.v:72" *)
  input clk;
  (* src = "src_verilog/mor1k_16Soc_top.v:73" *)
  input processors_en;
  (* src = "src_verilog/mor1k_16Soc_top.v:72" *)
  input reset;
endmodule
